# fly.toml app configuration file generated for scoutsense-api on 2025-02-23T07:02:19-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scoutsense-api'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# Single process that runs both API and worker via PM2
[[processes]]
  name = 'app'
  cmd = 'npx pm2-runtime start ecosystem.config.json'
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

# Worker process - only one instance to avoid Redis connection issues
[[processes]]
  name = 'worker'
  cmd = 'npx pm2-runtime start ecosystem.config.json'
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  count = 1  # Limit to a single worker instance

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['app', 'worker']  # Both processes can run on the same VM

# API Service
[[services]]
  internal_port = 3030
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "30s"
    method = "get"
    path = "/health"
    protocol = "http"
  
# Worker Service
[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["worker"]

  [[services.ports]]
    handlers = ["http"]
    port = "3000"

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "30s"
    method = "get"
    path = "/health"
    protocol = "http"

[deploy]
  release_command = "npx prisma migrate deploy"
